language: python

matrix:
  include:
    # - os: linux
    #   sudo: required
    #   python: 2.7
    #   env: TOX_ENV=docs
    - os: linux
      sudo: required
      python: 2.7
      env: TOX_ENV=lint
    # - os: linux
    #   sudo: required
    #   python: 2.7
    #   env: TOX_ENV=py27
    # - os: osx
    #   language: generic
    #   env: TOX_ENV=py27

install:
  - git submodule update --init --recursive
  - pip install -U pip setuptools tox pytest
  - hg --version

script:
  - py.test -vs tests/commands/test_lib.py
