language: python

matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
      env: TOX_ENV=docs
    - os: linux
      sudo: required
      python: 2.7
      env: TOX_ENV=lint
    - os: linux
      sudo: required
      python: 2.7
      env: TOX_ENV=py27
    - os: osx
      language: generic
      env: TOX_ENV=py27

install:
  - git submodule update --init --recursive
  - sudo pip install -U pip setuptools tox

  # temporary hook to fix issue with gcc-pic32
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq lib32z1 lib32ncurses5 lib32bz2-1.0; fi

script:
  - tox -e $TOX_ENV

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tox -e coverage; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  slack:
    secure: ksQmXOP5NVsf8IgoDuxD68Q/YNwDpZuwq0V29h2dxYCr38oYdAkq/Os4LSCs0X6P0cQFf6nC1hM/d+cAvU+SmzcHGxEceHNEGCg3/TAj+68KIwooPU93Lfq1zwdfteZWxANjKlCQy4+wZliHLhL8fvCYgfJww/6qKmqSYleBNM=
    on_failure: always
    on_success: change